version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT= 3000
    env_file:
      - ./.env
    volumes:
      - ./:/home/app
      - /home/app/node_modules

